@baseURL = http://localhost:6969
@authToken = {{authenticate.response.body.access_token}}

# @name create_account
POST {{baseURL}}/accounts
Content-type: application/json

{
  "name": "Raphael Vaz",
  "email": "raphael@wrath-codes.com",
  "password": "123456"
}

###

# @name authenticate
POST {{baseURL}}/sessions
Content-type: application/json

{
  "email": "raphael@wrath-codes.com",
  "password": "123456"
}

###

# @name create_question
POST {{baseURL}}/questions
Content-type: application/json
Authorization: Bearer {{authToken}}
