@baseURL = http://localhost:6969
@authToken = {{authenticate.response.body.access_token}}

# @name create_account
POST {{baseURL}}/accounts
Content-type: application/json

{
  "name": "Raphael Vaz",
  "email": "raphael@wrath-codes.com",
  "password": "123456"
}

###

# @name authenticate
POST {{baseURL}}/sessions
Content-type: application/json

{
  "email": "raphael@wrath-codes.com",
  "password": "123456"
}

###

# @name create_question
POST {{baseURL}}/questions
Content-type: application/json
Authorization: Bearer {{authToken}}

{
  "title": "How to create a question?",
  "content": "I'm trying to create a question using the API, but I don't know how to do it. Can someone help me?"
}

###

# @name create_question_2
POST {{baseURL}}/questions
Content-type: application/json
Authorization: Bearer {{authToken}}

{
  "title": "How to create a question 2?",
  "content": "I'm trying to create a question using the API, but I don't know how to do it. Can someone help me?"
}

###

# @name fetch_latest_questions
GET  {{baseURL}}/questions?page=2
Content-type: application/json
Authorization: Bearer {{authToken}}